volumes:
    langgraph-data:
        driver: local
    agent_memory_data:
services:
    langgraph-redis:
        image: redis:7
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-postgres:
        image: postgres:16
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s
    langgraph-api:
        image: ghcr.io/racenak/agent-data-pipeline-langgraph-api:latest
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            DATABASE_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable

    agent-memory:
      image: postgres:16
      environment:
        POSTGRES_DB: agent_memory
        POSTGRES_USER: agent
        POSTGRES_PASSWORD: agent
      volumes:
        - agent_memory_data:/var/lib/postgresql/data
      ports:
        - "5433:5432"
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U agent"]
        interval: 5s
        timeout: 5s
        retries: 5
