{
 "title": "Prefect / Flow Runs Overview",
 "description": "Dashboard for Prefect Exporter chart",
 "tags": [
  "prefect",
  "infrastructure",
  "chart",
  "monitoring",
  "flow-runs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(prefect_info_flows,namespace)"
    }
   },
   {
    "name": "flow_name",
    "label": "Flow Name",
    "query": {
     "query": "label_values(prefect_info_flows,flow_name)"
    }
   },
   {
    "name": "flow_run_name",
    "label": "Flow Run Name",
    "query": {
     "query": "label_values(prefect_info_flow_runs{flow_name=\"$flow_name\"},flow_run_name)"
    }
   },
   {
    "name": "flow_run_state_name",
    "label": "Flow Run State",
    "query": {
     "query": "label_values(prefect_info_flow_runs,state_name)"
    }
   },
   { "name": "search", "label": "Search" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flows total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prefect_flows_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deployments total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(prefect_deployments_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deployments paused",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prefect_info_deployment{is_schedule_active=\"False\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Runs running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(prefect_info_flow_runs == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Runs total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(prefect_info_flow_runs)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Flow Runs average run time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(prefect_flow_runs_total_run_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Runs by state",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (state_name) (prefect_info_flow_runs)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Flows Runs: $flow_name (last 24h)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Flow Runs total",
   "type": "stat",
   "description": "Last 24h",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(prefect_info_flow_runs{flow_name=~\"$flow_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 21, "x": 3, "y": 7 },
   "targets": [
    {
     "expr": "prefect_info_flow_runs{state_name=~\"$flow_run_state_name\", flow_name=~\"$flow_name\"}"
    }
   ]
  },
  {
   "title": "CPU usage peak",
   "type": "stat",
   "description": "Last 24h",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max(max_over_time(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\".*$flow_name.*\"}[$__range])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEM usage peak",
   "type": "stat",
   "description": "Last 24h",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max(max_over_time(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", container!=\"\", image!=\"\"}[$__range])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Average time",
   "type": "stat",
   "description": "Last 24h",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (flow_name) (prefect_flow_runs_total_run_time{flow_name=~\"$flow_name\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Run total run time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (flow_name) (prefect_flow_runs_total_run_time{flow_name=~\"$flow_name\"})",
     "legendFormat": "{{flow_run_name}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "prefect_info_flows{flow_name=~\"$flow_name\"} == 1"
    }
   ]
  },
  {
   "title": "CPU Usage $flow_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\", pod=~\".*$flow_name.*\"}) by (pod))",
     "legendFormat": "usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", resource=\"cpu\"}\n",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", resource=\"cpu\"}\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Memory Usage (WSS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", container!=\"\", image!=\"\"}) by (pod))",
     "legendFormat": "usage"
    },
    {
     "expr": "kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", resource=\"memory\"}",
     "legendFormat": "requests"
    },
    {
     "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=~\".*$flow_name.*\", resource=\"memory\"}",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Flow logs: flow-$flow_name",
   "type": "logs",
   "description": "Include all flow_runs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\".*$flow_name.*\"} |= \"$search\""
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "prefect_info_deployment{flow_name=~\"$flow_name\"}"
      }
     ]
    }
   ]
  }
 ]
}